# These are supported funding model platforms

# open_collective: # Replace with a single Open Collective username
custom: ['https://www.buymeacoffee.com/m97tA5c']
# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: cdimascio
