# These are supported funding model platforms

# open_collective: # Replace with a single Open Collective username
custom: ['https://www.buymeacoffee.com/m97tA5c']
# github: [CDIMASCIO]
# patreon: cdimascio
